version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=donotopen
    redis:
        image: 'redis:latest'
    nginx:
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        restart: always
        ports: 
            - '3050:80' # 3050 port to access from my machine
        depends_on: 
            - api
            - client
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules #to preserve this folder, dont override it
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=donotopen
            - PGPORT=5432
        depends_on:
            - postgres
            - redis
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules #to preserve this folder, dont override it
            - ./client:/app
        depends_on:
            - api
            - worker
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules #to preserve this folder, dont override it
            - ./worker :/app
        depends_on:
            - api
            - redis
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379